### PR TITLE
feat: add rust-semver

### PR DESCRIPTION
**Pull request by Starains320**
the source for the Rust semver crate

Log: add rust-semver
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/134

### CODE REVIEW

**Comment by Starains320** [comment]
@chenchongbiao 请老师检查

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，pr的格式已改

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
